### ISSUE TITLE
SwiftyRequest crashes randomly on Linux due to NSUnimplemented

### ISSUE THREAD

**Issue by mman** [IBM-Swift/SwiftyRequest#25] opened 2018-05-03 13:15 UTC
Using SwiftyRequest in production randomly crashes the process with

```
Fatal error: seekInputStream(to:) is not yet implemented: file Foundation/URLSession/NativeProtocol.swift, line 264
```

Not sure where is this called from but looks like somewhere deep in Linux URLSession code, not necessarily the SwiftyRequest code.

**Comment by ianpartridge** [comment] 2018-07-09 13:11
Hmm yes I think this is a limitation in the current implementation of URLSession on Linux. @pushkarnk @nethraravindran do you have any thoughts on this? Could we implement seekInputStream()?

**Comment by ianpartridge** [comment] 2018-08-17 16:11
As this is not a SwiftyRequest issue per se but caused by the implementation of URLSession on Linux I'm closing this for now.

**Closed by ianpartridge** 2018-08-17 16:11 UTC

**Comment by mman** [comment] 2018-10-11 08:58
This issue should not be closed as it falsely leads people to believe that SwiftyRequest works on Linux, whereas if I am not missing anything it still randomly crashes via `NSUnimplemented` as `seekInputStream()` still remains unimplemented. Thus using this library on Linux will crash randomly as of swift 4.2.

**Comment by ianpartridge** [comment] 2018-10-11 09:08
I'd accept PRs updating the documentation to make this clearer.  However, `seekInputStream()` is [in the process of being implemented](https://github.com/apple/swift-corelibs-foundation/pull/1629) so this is all going to resolve itself in due course.

**Comment by mman** [comment] 2018-10-11 09:37
Whatever works for you @ianpartridge. It's just that I came back after 6 months and almost accidentally pulled in SwiftyRequest believing it's all good and shiny while it still crashes.

**Comment by ianpartridge** [comment] 2018-10-11 11:42
That's fair. I've just [updated the README](https://github.com/IBM-Swift/SwiftyRequest/commit/d52651e68c485aca292db280daae0c22642f273b) to warn people accordingly.  Thank you.

**Comment by mman** [comment] 2018-10-11 11:45
@ianpartridge 👍

**Comment by hyouuu** [comment] 2019-04-25 18:52
Do you guys know why it happens randomly and not every time?

**Comment by hyouuu** [comment] 2019-04-25 19:08
<img width="1616" alt="Screen Shot 2019-04-25 at 12 06 06 PM" src="https://user-images.githubusercontent.com/5061867/56761690-d92b8d00-6752-11e9-9ca0-79ab89a8ea73.png">

Found someone's explanation for anyone interested
